-- Drop table

-- DROP TABLE public.cliente;

CREATE TABLE cliente (
	id_cliente int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NULL,
	email varchar(255) NULL,
	CONSTRAINT customer_pk PRIMARY KEY (id_cliente)
);
